# https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

blank_issues_enabled: false
contact_links:
  - name: Build-Test-Release backlog
    url: https://github.com/openedx/build-test-release-wg/projects/1
    about: Tickets for work on community releases
  - name: Build-Test-Release discussions
    url: https://discuss.openedx.org/c/working-groups/build-test-release/30
    about: Discussions about creating Open edX community releases
  - name: Ops discussion
    url: https://discuss.openedx.org/c/devops/ops-help/27
    about: General help with operating Open edX instances
